"""
pronunciation_mapper.py - Transforma comandos de terminal en texto pronunciable por TTS
Sistema de pronunciación profesional para KR-STUDIO
"""

import re
import logging

logger = logging.getLogger(__name__)

# Mapeo de comandos comunes
COMMAND_MAP = {
    # Comandos de red
    "nmap": "enemap",
    "netstat": "netstat",
    "curl": "curl",
    "wget": "wguet",
    "ping": "ping",
    "traceroute": "traceroute",
    "mtr": "em tr",
    "nslookup": "enes lookup",
    "dig": "dig",
    "host": "host",
    "whois": "who is",
    "arp": "arp",
    "route": "route",
    "ifconfig": "ifconfig",
    "ip": "ip",
    "ss": "ess ess",
    # Comandos de sistema
    "sudo": "sudo",
    "su": "ess u",
    "chmod": "chmod",
    "chown": "chown",
    "chgrp": "chgrp",
    "ls": "eles",
    "ll": "eles eles",
    "la": "eles a",
    "cd": "ce de",
    "pwd": "peuve de",
    "cat": "cat",
    "grep": "grep",
    "awk": "awk",
    "sed": "sed",
    "cut": "cut",
    "sort": "sort",
    "uniq": "uniq",
    "wc": "uve ce",
    "head": "head",
    "tail": "tail",
    "less": "less",
    "more": "more",
    "find": "find",
    "locate": "locate",
    "which": "which",
    "whereis": "where is",
    "type": "type",
    "file": "file",
    "stat": "stat",
    "touch": "touch",
    "mkdir": "make dir",
    "rmdir": "remove dir",
    "rm": "remove",
    "cp": "cp",
    "mv": "mv",
    "ln": "ln",
    "readlink": "readlink",
    "realpath": "real path",
    "tar": "tar",
    "gzip": "gzip",
    "gunzip": "ungzip",
    "zip": "zip",
    "unzip": "unzip",
    "7z": "seven zee",
    # Comandos de procesos
    "ps": "pe ess",
    "top": "top",
    "htop": "aitch top",
    "kill": "kill",
    "killall": "kill all",
    "pkill": "pkill",
    "jobs": "jobs",
    "fg": "ef ge",
    "bg": "bee ge",
    "nice": "nice",
    "renice": "re nice",
    # Comandos de usuarios
    "useradd": "user add",
    "usermod": "user mod",
    "userdel": "user del",
    "groupadd": "group add",
    "groupdel": "group del",
    "passwd": "passwd",
    "id": "id",
    "whoami": "who am i",
    "who": "who",
    "w": "uve",
    "last": "last",
    # Comandos de paquetes
    "apt": "apt",
    "apt-get": "apt get",
    "apt-cache": "apt cache",
    "dpkg": "dpkg",
    "yum": "yum",
    "dnf": "dnf",
    "rpm": "rpm",
    "pacman": "pacman",
    "pip": "pip",
    "pip3": "pip tres",
    "npm": "en em pe",
    "yarn": "yarn",
    "conda": "conda",
    # Comandos Docker
    "docker": "docker",
    "docker-compose": "docker compose",
    "kubectl": "kube ctl",
    "helm": "helm",
    "podman": "podman",
    # Comandos Git
    "git": "git",
    "git clone": "git clone",
    "git pull": "git pull",
    "git push": "git push",
    "git commit": "git commit",
    "git checkout": "git checkout",
    "git branch": "git branch",
    "git merge": "git merge",
    "git rebase": "git rebase",
    "git status": "git status",
    "git log": "git log",
    "git diff": "git diff",
    # Lenguajes y frameworks
    "python": "python",
    "python3": "python tres",
    "ruby": "ruby",
    "perl": "perl",
    "php": "pe aitch pe",
    "java": "java",
    "javac": "javac",
    "node": "node",
    "npm": "en em pe",
    "gcc": "gee cee cee",
    "g++": "gee plus plus",
    "make": "make",
    "cmake": "cmake",
    "go": "go",
    "rustc": "rustc",
    "cargo": "cargo",
    # Herramientas de seguridad
    "metasploit": "metasploit",
    "msfconsole": "emesf console",
    "msfvenom": "emesf venóm",
    "nikto": "nikto",
    "dirb": "dirb",
    "gobuster": "go buster",
    "wfuzz": "double ef fuzz",
    "sqlmap": "sql map",
    "hydra": "hydra",
    "john": "john",
    "hashcat": "hashcat",
    "aircrack": "aircrack",
    "reaver": "reaver",
    "wireshark": "wire shark",
    "tcpdump": "tcp dump",
    "ettercap": "ettercap",
    "ncat": "en cat",
    "netcat": "netcat",
    "socat": "socat",
    "openssl": "open ess ell",
    "ssh": "ess ess aitch",
    "scp": "ess ce pe",
    "rsync": "ar sync",
    "ftp": "efe te pe",
    "sftp": "ess efe te pe",
    "telnet": "telnet",
    # Herramientas de monitoreo
    "htop": "aitch top",
    "iotop": "io top",
    "atop": "a top",
    "glances": "glances",
    "bashtop": "bash top",
    "bpytop": "bpi top",
    "neofetch": "neo fetch",
    "screenfetch": "screen fetch",
    "vmstat": "vee em stat",
    "iostat": "io stat",
    "mpstat": "emp stat",
    "sar": "esar",
    "nmon": "enemon",
    "dstat": "de stat",
    # Misc
    "man": "man",
    "info": "info",
    "help": "help",
    "echo": "echo",
    "printf": "printf",
    "source": "source",
    "export": "export",
    "alias": "alias",
    "unalias": "unalias",
    "env": "env",
    "set": "set",
    "unset": "unset",
    "read": "read",
    "test": "test",
    "true": "true",
    "false": "false",
    "exit": "exit",
    "logout": "logout",
    "clear": "clear",
    "reset": "reset",
    "history": "history",
    "xargs": "xargs",
    "tee": "tee",
}

# Mapeo de flags comunes
FLAG_MAP = {
    # Flags cortos comunes
    "-sS": "menos ese ess",
    "-sV": "menos ese ve",
    "-sC": "menos ese ce",
    "-sU": "menos ese u",
    "-sT": "menos ese te",
    "-sP": "menos ese pe",
    "-sN": "menos ese ene",
    "-Pn": "menos pe ene",
    "-PO": "menos pe o",
    "-PU": "menos pe u",
    "-PA": "menos pe a",
    "-A": "menos a",
    "-O": "menos o",
    "-p": "menos pe",
    "-P": "menos pe mayúscula",
    "-p-": "menos pe menos",
    "-f": "menos efe",
    "-F": "menos efe mayúscula",
    "-v": "menos ve",
    "-vv": "menos ve ve",
    "-vvv": "menos ve ve ve",
    "-d": "menos de",
    "-dd": "menos de de",
    "-ddd": "menos de de de",
    "-o": "menos o",
    "-oA": "menos o a",
    "-oN": "menos o ene",
    "-oX": "menos o equis",
    "-oG": "menos o ge",
    "-i": "menos i",
    "-iL": "menos i ele",
    "-iR": "menos i erre",
    "-R": "menos erre",
    "-n": "menos ene",
    "-N": "menos ene mayúscula",
    "-r": "menos erre",
    "-T": "menos te",
    "-T1": "menos te uno",
    "-T2": "menos te dos",
    "-T3": "menos te tres",
    "-T4": "menos te cuatro",
    "-T5": "menos te cinco",
    "-e": "menos e",
    "-E": "menos e mayúscula",
    "-M": "menos eme",
    "-D": "menos de",
    "-b": "menos be",
    "-g": "menos ge",
    "-h": "menos ache",
    "-H": "menos ache mayúscula",
    "-l": "menos ele",
    "-L": "menos ele mayúscula",
    "-z": "menos zed",
    "-X": "menos equis",
    "-u": "menos u",
    "-U": "menos u mayúscula",
    "-w": "menos uve",
    "-W": "menos uve mayúscula",
    "-t": "menos te",
    "-m": "menos eme",
    "-c": "menos ce",
    "-C": "menos ce mayúscula",
    "-B": "menos be mayúscula",
    "-I": "menos i mayúscula",
    "-j": "menos jota",
    "-J": "menos jota mayúscula",
    "-k": "menos ka",
    "-K": "menos ka mayúscula",
    "-q": "menos cu",
    "-Q": "menos cu mayúscula",
    "-V": "menos ve mayúscula",
    "-y": "menos i greca",
    "-Y": "menos i greca mayúscula",
    "-0": "menos cero",
    "-1": "menos uno",
    "-2": "menos dos",
    "-3": "menos tres",
    "-4": "menos cuatro",
    "-5": "menos cinco",
    "-6": "menos seis",
    "-7": "menos siete",
    "-8": "menos ocho",
    "-9": "menos nueve",
    # Flags largos (--)
    "--help": "guion guion help",
    "--version": "guion guion version",
    "--verbose": "guion guion verbose",
    "--force": "guion guion force",
    "--all": "guion guion all",
    "--recursive": "guion guion recursive",
    "--long": "guion guion long",
    "--human-readable": "guion guion human readable",
    "--color": "guion guion color",
    "--quiet": "guion guion quiet",
    "--silent": "guion guion silent",
    "--output": "guion guion output",
    "--input": "guion guion input",
    "--format": "guion guion format",
    "--json": "guion guion json",
    "--xml": "guion guion xml",
    "--yaml": "guion guion yaml",
    "--tcp": "guion guion tcp",
    "--udp": "guion guion udp",
    "--icmp": "guion guion icmp",
    "--http": "guion guion http",
    "--https": "guion guion https",
    "--ftp": "guion guion ftp",
    "--ssh": "guion guion ssh",
    "--telnet": "guion guion telnet",
    "--smtp": "guion guion smtp",
    "--dns": "guion guion dns",
    "--ntp": "guion guion ntp",
    "--snmp": "guion guion snmp",
    "--mysql": "guion guion mysql",
    "--postgres": "guion guion postgres",
    "--mongodb": "guion guion mongodb",
    "--redis": "guion guion redis",
    "--docker": "guion guion docker",
    "--kubernetes": "guion guion kubernetes",
    "--namespace": "guion guion namespace",
    "--pod": "guion guion pod",
    "--service": "guion guion service",
    "--ingress": "guion guion ingress",
    "--config": "guion guion config",
    "--file": "guion guion file",
    "--directory": "guion guion directory",
    "--symlink": "guion guion symlink",
    "--owner": "guion guion owner",
    "--group": "guion guion group",
    "--permission": "guion guion permission",
    "--mode": "guion guion mode",
    "--user": "guion guion user",
    "--password": "guion guion password",
    "--host": "guion guion host",
    "--port": "guion guion port",
    "--protocol": "guion guion protocol",
    "--method": "guion guion method",
    "--header": "guion guion header",
    "--body": "guion guion body",
    "--cookie": "guion guion cookie",
    "--session": "guion guion session",
    "--token": "guion guion token",
    "--auth": "guion guion auth",
    "--cert": "guion guion cert",
    "--key": "guion guion key",
    "--ca": "guion guion ca",
    "--insecure": "guion guion insecure",
    "--follow": "guion guion follow",
    "--redirect": "guion guion redirect",
    "--proxy": "guion guion proxy",
    "--timeout": "guion guion timeout",
    "--retry": "guion guion retry",
    "--parallel": "guion guion parallel",
    "--thread": "guion guion thread",
    "--process": "guion guion process",
    "--daemon": "guion guion daemon",
    "--background": "guion guion background",
    "--foreground": "guion guion foreground",
    "--interactive": "guion guion interactive",
    "--batch": "guion guion batch",
    "--script": "guion guion script",
    "--command": "guion guion command",
    "--shell": "guion guion shell",
    "--terminal": "guion guion terminal",
    "--tty": "guion guion tty",
    "--pty": "guion guion pty",
    "--env": "guion guion env",
    "--var": "guion guion var",
    "--export": "guion guion export",
    "--source": "guion guion source",
    "--alias": "guion guion alias",
    "--function": "guion guion function",
    "--builtin": "guion guion builtin",
    "--executable": "guion guion executable",
    "--shared": "guion guion shared",
    "--static": "guion guion static",
    "--dynamic": "guion guion dynamic",
    "--debug": "guion guion debug",
    "--trace": "guion guion trace",
    "--profile": "guion guion profile",
    "--benchmark": "guion guion benchmark",
    "--test": "guion guion test",
    "--spec": "guion guion spec",
    "--suite": "guion guion suite",
    "--unit": "guion guion unit",
    "--integration": "guion guion integration",
    "--functional": "guion guion functional",
    "--end-to-end": "guion guion end to end",
    "--smoke": "guion guion smoke",
    "--sanity": "guion guion sanity",
    "--regression": "guion guion regression",
    "--performance": "guion guion performance",
    "--load": "guion guion load",
    "--stress": "guion guion stress",
    "--security": "guion guion security",
    "--vulnerability": "guion guion vulnerability",
    "--penetration": "guion guion penetration",
    "--exploit": "guion guion exploit",
    "--payload": "guion guion payload",
    "--shellcode": "guion guion shellcode",
    "--backdoor": "guion guion backdoor",
    "--trojan": "guion guion trojan",
    "--virus": "guion guion virus",
    "--worm": "guion guion worm",
    "--malware": "guion guion malware",
    "--ransomware": "guion guion ransomware",
    "--spyware": "guion guion spyware",
    "--adware": "guion guionware",
    "--rootkit": "guion guion rootkit",
    "--keylogger": "guion guion keylogger",
    "--phishing": "guion guion phishing",
    "--spoofing": "guion guion spoofing",
    "--sniffing": "guion guion sniffing",
    "--spoofing": "guion guion spoofing",
    "--mitm": "guion guion mitm",
    "--dos": "guion guion dos",
    "--ddos": "guion guion ddos",
    "--bruteforce": "guion guion bruteforce",
    "--dictionary": "guion guion dictionary",
    "--rainbow": "guion guion rainbow",
    "--wordlist": "guion guion wordlist",
    "--mask": "guion guion mask",
    "--hybrid": "guion guion hybrid",
    "--rule": "guion guion rule",
}

# Mapeo de símbolos
SYMBOL_MAP = {
    # Rutas
    "./": "punto barra",
    "../": "punto punto barra",
    "~": "tilde",
    "~/.bashrc": "tilde barra punto bashrc",
    "~/": "tilde barra",
    # Operadores
    "|": "pipe",
    "||": "or or",
    "&&": "and and",
    ">": "mayor que",
    ">>": "mayor mayor que",
    "<": "menor que",
    "<<": "menor menor que",
    "2>": "dos mayor que",
    "2>>": "dos mayor mayor que",
    "&>": "and mayor que",
    ">&": "mayor and",
    ";": "punto y coma",
    "::": "dos puntos",
    "=": "igual",
    "==": "igual igual",
    "!=": "no igual",
    "+": "más",
    "-": "menos",
    "*": "asterisco",
    "/": "barra",
    "%": "porcentaje",
    "^": "acento",
    "&": "ampersand",
    "~": "tilde",
    "`": "backtick",
    "$": "dólar",
    "@": "arrobá",
    "!": "exclamación",
    "?": "interrogación",
    "#": "hash",
    "_": "guion bajo",
    "-": "guion",
    "--": "guion guion",
    "...": "puntos suspensivos",
    # Paréntesis y brackets
    "(": "paréntesis abre",
    ")": "paréntesis cierra",
    "[": "corchete abre",
    "]": "corchete cierra",
    "{": "llave abre",
    "}": "llave cierra",
    # Comillas
    '"': "comillas dobles",
    "'": "comilla simple",
    "`": "backtick",
    # Wildcards
    "*": "asterisco",
    "?": "interrogación",
    "**": "asterisco asterisco",
}

# Mapeo de extensiones
EXTENSION_MAP = {
    ".sh": "punto shell",
    ".bash": "punto bash",
    ".zsh": "punto z shell",
    ".py": "punto python",
    ".js": "punto j s",
    ".ts": "punto t s",
    ".jsx": "punto j s x",
    ".tsx": "punto t s x",
    ".java": "punto java",
    ".c": "punto ce",
    ".cpp": "punto ce plus plus",
    ".h": "punto hache",
    ".hpp": "punto hache plus plus",
    ".go": "punto go",
    ".rs": "punto r s",
    ".rb": "punto r b",
    ".php": "punto pe aitch pe",
    ".swift": "punto swift",
    ".kt": "punto ka te",
    ".scala": "punto scala",
    ".json": "punto json",
    ".xml": "punto xml",
    ".yaml": "punto yaml",
    ".yml": "punto yml",
    ".toml": "punto toml",
    ".ini": "punto ini",
    ".conf": "punto conf",
    ".config": "punto config",
    ".txt": "punto txt",
    ".md": "punto md",
    ".rst": "punto r s t",
    ".log": "punto log",
    ".csv": "punto csv",
    ".tsv": "punto t s v",
    ".sql": "punto sql",
    ".db": "punto d b",
    ".sqlite": "punto sqlite",
    ".mdb": "punto m d b",
    # Web
    ".html": "punto html",
    ".htm": "punto h t m",
    ".css": "punto c s s",
    ".scss": "punto s c s s",
    ".sass": "punto sass",
    ".less": "punto less",
    ".vue": "punto vue",
    ".svelte": "punto svelte",
    # Imágenes
    ".jpg": "punto jpg",
    ".jpeg": "punto jpeg",
    ".png": "punto png",
    ".gif": "punto gif",
    ".bmp": "punto b m p",
    ".svg": "punto s v g",
    ".ico": "punto ico",
    ".webp": "punto webp",
    # Video/Audio
    ".mp4": "punto mp cuatro",
    ".avi": "punto avi",
    ".mkv": "punto mkv",
    ".mov": "punto mov",
    ".webm": "punto webm",
    ".mp3": "punto mp tres",
    ".wav": "punto wav",
    ".flac": "punto flac",
    ".ogg": "punto ogg",
    ".m4a": "punto m cuatro a",
    # Comprimidos
    ".zip": "punto zip",
    ".rar": "punto rar",
    ".7z": "punto siete z",
    ".tar": "punto tar",
    ".gz": "punto g z",
    ".bz2": "punto b z dos",
    ".xz": "punto x z",
    ".tgz": "punto t g z",
    # Ejecutables
    ".exe": "punto exe",
    ".dll": "punto dll",
    ".so": "punto s o",
    ".dylib": "punto dylib",
    ".bin": "punto bin",
    ".app": "punto app",
    ".deb": "punto deb",
    ".rpm": "punto rpm",
    ".apk": "punto apk",
    ".ipa": "punto ipa",
    # Docs
    ".pdf": "punto pdf",
    ".doc": "punto doc",
    ".docx": "punto docx",
    ".xls": "punto xls",
    ".xlsx": "punto xlsx",
    ".ppt": "punto p p t",
    ".pptx": "punto p p t x",
    ".odt": "punto o d t",
    ".ods": "punto o d s",
    ".odp": "punto o d p",
}

# Mapeo de IPs y puertos comunes
NETWORK_MAP = {
    "localhost": "localhost",
    "127.0.0.1": "uno dos siete punto cero punto cero punto uno",
    "0.0.0.0": "cero punto cero punto cero punto cero",
    "255.255.255.0": "dos cinco cinco punto dos cinco cinco punto dos cinco cinco punto cero",
    "/etc/passwd": "slash etc slash passwd",
    "/etc/shadow": "slash etc slash shadow",
    "/etc/hosts": "slash etc slash hosts",
    "/var/log": "slash var slash log",
    "/tmp": "slash tmp",
    "/root": "slash root",
    "/home": "slash home",
    "/usr": "slash usr",
    "/bin": "slash bin",
    "/sbin": "slash sbin",
    "/opt": "slash opt",
    "/var": "slash var",
    "/srv": "slash srv",
    "/proc": "slash proc",
    "/sys": "slash sys",
    "/dev": "slash dev",
}


def transform_to_pronounceable(text: str) -> str:
    """
    Transforma texto con comandos, flags y símbolos en versión pronunciable.
    """
    if not text:
        return text
    
    # Preserve compound commands first
    text = text.replace("apt-get", "APTGET")
    text = text.replace("git-push", "GITPUSH")
    text = text.replace("git-pull", "GITPULL")
    
    result = text
    
    # URLs - just remove them or replace with placeholder
    result = result.replace("https://", " HTTPS ")
    result = result.replace("http://", " HTTP ")
    
    # Paths
    result = result.replace("./", " punto barra ")
    result = result.replace("../", " punto punto barra ")
    
    # Extensions
    replacements = [
        (".sh", "punto shell"),
        (".py", "punto python"),
        (".js", "punto j s"),
        (".json", "punto json"),
        (".txt", "punto txt"),
        (".log", "punto log"),
        (".conf", "punto conf"),
        (".xml", "punto xml"),
        (".yaml", "punto yaml"),
        (".yml", "punto yml"),
    ]
    for old, new in replacements:
        result = result.replace(old, " " + new + " ")
    
    # Common flags - order matters!
    flag_replacements = [
        ("-sV", "menos ese ve"),
        ("-sC", "menos ese ce"),
        ("-sU", "menos ese u"),
        ("-sT", "menos ese te"),
        ("-sP", "menos ese pe"),
        ("-sN", "menos ese ene"),
        ("-Pn", "menos pe ene"),
        ("-PO", "menos pe o"),
        ("-PA", "menos pe a"),
        ("-PU", "menos pe u"),
        ("-A", "menos a"),
        ("-O", "menos o"),
        ("-p", "menos pe"),
        ("-f", "menos efe"),
        ("-v", "menos ve"),
        ("-vv", "menos ve ve"),
        ("-oN", "menos o ene"),
        ("-oX", "menos o equis"),
        ("-oG", "menos o ge"),
        ("-iL", "menos i ele"),
        ("-n", "menos ene"),
        ("-r", "menos erre"),
        ("-T4", "menos te cuatro"),
        ("-T3", "menos te tres"),
        ("-T2", "menos te dos"),
        ("-T1", "menos te uno"),
        ("-e", "menos e"),
        ("-M", "menos eme"),
        ("-D", "menos de"),
        ("-b", "menos be"),
        ("-g", "menos ge"),
        ("-h", "menos ache"),
        ("-l", "menos ele"),
        ("-z", "menos zed"),
        ("-X", "menos equis"),
        ("-u", "menos u"),
        ("-w", "menos uve"),
        ("-t", "menos te"),
        ("-m", "menos eme"),
        ("-c", "menos ce"),
        ("-m", "menos eme"),
    ]
    for old, new in flag_replacements:
        result = result.replace(old, new)
    
    # Single dash flags
    result = re.sub(r'-([a-zA-Z0-9])', r' menos ', result)
    
    # Commands
    cmd_replacements = [
        ("nmap", "enemap"),
        ("netstat", "netstat"),
        ("curl", "curl"),
        ("wget", "wguet"),
        ("sudo", "sudo"),
        ("docker", "docker"),
        ("kubectl", "kube ctl"),
        ("git", "git"),
        ("python", "python"),
        ("python3", "python tres"),
        ("pip", "pip"),
        ("pip3", "pip tres"),
        ("apt-get", "aptget"),
        ("apt", "apt"),
        ("npm", "en em pe"),
        ("make", "make"),
        ("gcc", "gee cee cee"),
        ("kubectl", "kube ctl"),
        ("ps", "pe ess"),
        ("ls", "eles"),
        ("cd", "ce de"),
        ("pwd", "peuve de"),
        ("cat", "cat"),
        ("grep", "grep"),
        ("chmod", "chmod"),
        ("chown", "chown"),
        ("ssh", "ess ess aitch"),
        ("scp", "ess ce pe"),
        ("ftp", "efe te pe"),
    ]
    for old, new in cmd_replacements:
        result = result.replace(old, new)
    
    # Symbols
    sym_replacements = [
        ("|", " pipe "),
        ("&&", " and and "),
        ("||", " or or "),
        (">>", " mayor mayor que "),
        (">", " mayor que "),
        ("<", " menor que "),
        (";", " punto y coma "),
        (":", " dos puntos "),
    ]
    for old, new in sym_replacements:
        result = result.replace(old, new)
    
    # Clean up
    # Restore compound commands
    result = result.replace("APTGET", "apt get")
    result = result.replace("GITPUSH", "git push")
    result = result.replace("GITPULL", "git pull")
    
    result = re.sub(r'\s+', ' ', result)
    return result.strip()



def transform_command_for_tts(comando: str, voz_text: str = None) -> tuple:
    """
    Transforma un comando para visualización y genera texto pronunciable.

    Returns:
        (comando_original, texto_pronunciable)
    """
    comando_original = comando

    # Generar versión pronunciable del comando
    comando_pronunciable = transform_to_pronounceable(comando)

    # Si hay texto de voz, también transformarlo
    voz_pronunciable = ""
    if voz_text:
        voz_pronunciable = transform_to_pronounceable(voz_text)

    return comando_original, comando_pronunciable, voz_pronunciable


def is_command_text(text: str) -> bool:
    """
    Detecta si el texto contiene comandos de terminal.
    """
    # Patrones comunes de comandos
    patterns = [
        r"^nmap\s",
        r"^curl\s",
        r"^wget\s",
        r"^sudo\s",
        r"^docker\s",
        r"^kubectl\s",
        r"^git\s",
        r"^python\s",
        r"^pip\s",
        r"^apt\s",
        r"^yum\s",
        r"^npm\s",
        r"^make\s",
        r"^gcc\s",
        r"-\w+",  # flags
        r"\|",  # pipe
        r"\s&&\s",  # chain
        r"\./",  # relative path
    ]

    for pattern in patterns:
        if re.search(pattern, text):
            return True

    return False
